//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bludo_Zakaz
    {
        public int id { get; set; }
        public Nullable<int> id_bludo { get; set; }
        public Nullable<int> id_zakaza { get; set; }
    
        public virtual Bludo_KAFE Bludo_KAFE { get; set; }
        public virtual Zakaz_KAFE Zakaz_KAFE { get; set; }
    }
}
