//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bludo_KAFE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bludo_KAFE()
        {
            this.Bludo_Zakaz = new HashSet<Bludo_Zakaz>();
        }
    
        public int id_bludo { get; set; }
        public string Nazvanie { get; set; }
        public string Stoimost { get; set; }
        public string Ves { get; set; }
        public string Sostav { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bludo_Zakaz> Bludo_Zakaz { get; set; }
    }
}
