//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user149_dbEntities : DbContext
    {
        public user149_dbEntities()
            : base("name=user149_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_KAFE> Admin_KAFE { get; set; }
        public virtual DbSet<Bludo_KAFE> Bludo_KAFE { get; set; }
        public virtual DbSet<Role_KAFE> Role_KAFE { get; set; }
        public virtual DbSet<Smena_KAFE> Smena_KAFE { get; set; }
        public virtual DbSet<Status_KAFE> Status_KAFE { get; set; }
        public virtual DbSet<Stolic_KAFE> Stolic_KAFE { get; set; }
        public virtual DbSet<User_KAFE> User_KAFE { get; set; }
        public virtual DbSet<Bludo_Zakaz> Bludo_Zakaz { get; set; }
        public virtual DbSet<Sotrudniki_Smena_KAFE> Sotrudniki_Smena_KAFE { get; set; }
        public virtual DbSet<Status_Zakaz_KAFE> Status_Zakaz_KAFE { get; set; }
        public virtual DbSet<Zakaz_KAFE> Zakaz_KAFE { get; set; }
    }
}
