//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smena_KAFE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smena_KAFE()
        {
            this.Sotrudniki_Smena_KAFE = new HashSet<Sotrudniki_Smena_KAFE>();
        }
    
        public int id_smeni { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Vremya { get; set; }
        public Nullable<int> id_admin { get; set; }
    
        public virtual Admin_KAFE Admin_KAFE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudniki_Smena_KAFE> Sotrudniki_Smena_KAFE { get; set; }
    }
}
