//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Sotrudniki_Smena_KAFE
    {
        user149_dbEntities db = new user149_dbEntities();
        public int id { get; set; }
        public Nullable<int> id_smeni { get; set; }
        public Nullable<int> id_user { get; set; }
        
        public string smena
        {
            get
            {
                var selectSmena = db.Sotrudniki_Smena_KAFE.Where(w => w.id_user == id_user).Select(w => w.id_smeni).FirstOrDefault();
                return Convert.ToString(selectSmena.Value);
            }
            set
            {
                var UserSmena = db.Sotrudniki_Smena_KAFE.Where(w => w.id_user == id_user).Select(w => w.id_smeni).FirstOrDefault(); ;
                if (UserSmena != null)
                {
                    UserSmena = Convert.ToInt32(value);
                }
                else { smena = "Нет смены";}
            }
        }
        public virtual Smena_KAFE Smena_KAFE { get; set; }
        public virtual User_KAFE User_KAFE { get; set; }
    }
}
