//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_KAFE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_KAFE()
        {
            this.Sotrudniki_Smena_KAFE = new HashSet<Sotrudniki_Smena_KAFE>();
            this.Zakaz_KAFE = new HashSet<Zakaz_KAFE>();
        }
    
        public int id_user { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> Role { get; set; }
        public string Telephone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> id_status { get; set; }
    
        public virtual Role_KAFE Role_KAFE { get; set; }
        public virtual Status_KAFE Status_KAFE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudniki_Smena_KAFE> Sotrudniki_Smena_KAFE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz_KAFE> Zakaz_KAFE { get; set; }
    }
}
