//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz_KAFE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz_KAFE()
        {
            this.Bludo_Zakaz = new HashSet<Bludo_Zakaz>();
        }
    
        public int id_zakaz { get; set; }
        public Nullable<int> id_stolic { get; set; }
        public Nullable<int> kol_vo_klientov { get; set; }
        public Nullable<int> Stoimost { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<System.DateTime> Vrema { get; set; }
        public Nullable<int> id_bludo { get; set; }
        public Nullable<int> id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bludo_Zakaz> Bludo_Zakaz { get; set; }
        public virtual Status_Zakaz_KAFE Status_Zakaz_KAFE { get; set; }
        public virtual Stolic_KAFE Stolic_KAFE { get; set; }
        public virtual User_KAFE User_KAFE { get; set; }
    }
}
